services:
  # Base de datos PostgreSQL para desarrollo
  db:
    image: postgres:13
    container_name: seguimiento-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: seguimiento_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - seguimiento-network-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Aplicación NestJS en modo desarrollo
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: seguimiento-backend-dev
    restart: always
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      PORT: 3001
      DB_URL: postgres://postgres:123@db:5432/seguimiento_db
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: 123
      DB_DATABASE: seguimiento_db
    volumes:
      - ./uploads:/app/uploads
      - ./temp:/app/temp
      # - .:/app
      # - /app/node_modules
      # - /app/dist
    depends_on:
      db:
        condition: service_healthy
    networks:
      - seguimiento-network-dev

networks:
  seguimiento-network-dev:
    driver: bridge

volumes:
  postgres_data_dev: